### ISSUE TITLE
Missing progress information

### ISSUE THREAD

**Issue by mdjdev** [playwrightsolutions/playwright-json-summary-reporter#5]
Hi, when enabling this reporter I do not see any progress information in the console anymore. Is this a wanted feature or a bug?

Without `playwright-json-summary-reporter`:
![2023-10-12_15-01](https://github.com/playwrightsolutions/playwright-json-summary-reporter/assets/18183474/51405995-70f0-42ba-9906-d43c3080513f)

With `playwright-json-summary-reporter`:
![2023-10-12_15-01_1](https://github.com/playwrightsolutions/playwright-json-summary-reporter/assets/18183474/1754f889-f4af-456c-857a-297be75f3ae3)

Thanks & best regards!

**Comment by BMayhew** [comment]
@mdjdev sorry for the lat response, but this isn't a feature I plan on adding for the json-summary-reporter. you can however include multiple reporters in your playwright config, so you still get this functionality from other reporters.

example below would include all the following reporters.

```
reporter: [["playwright-json-summary-reporter"], ["github"], ["list"], ["html"]]
```
